#!/bin/bash

shopt -s nullglob

if [ -e ./toolspath ];then
	. ./toolspath
else
	./setuptools
fi

if [[ $RECOMPILEHEADER -eq 1 ]];then
	pushd KKEditQT/src
		echo "Compiling headers ..."
		echo g++ -c $(pkg-config --cflags Qt6Core Qt6Widgets Qt6Gui Qt6PrintSupport sqlite3) -fPIC -x  c++-header qtincs.h -o qtincs.h.gch
		g++ -c $(pkg-config --cflags Qt6Core Qt6Widgets Qt6Gui  Qt6PrintSupport sqlite3) -fPIC -x  c++-header qtincs.h -o qtincs.h.gch
	popd
fi

cd "KKEditQT/src"

csrclst=$(echo "../src/*.c" "../src/*.cpp")
echo COMMONSRC = $csrclst > ../sources

exit 0
