#!/bin/bash -e

#©keithhedger Sat 15 Jun 13:51:13 BST 2024 kdhedger68713@gmail.com

QMAKEPATH="$(qtchooser -run-tool=qmake -qt=qt6 -query QT_INSTALL_BINS)/qmake"
if [[ ! -e "${QMAKEPATH}" ]];then
	echo "Can't find QT6 version of qmake please set QMAKEPATH in ./toolspath manually, or install QT6."
	exit 1
fi

echo "QMAKEPATH=$QMAKEPATH" > ./toolspath
echo "export QMAKEPATH" >> ./toolspath
