#!/bin/bash
#
#©K. D. Hedger. Mon 29 Jul 12:06:32 BST 2024 keithdhedger@gmail.com
#
#This file (makedocset) is part of KKEditQT.
#
#KKEditQT is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#KKEditQT is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with KKEditQT.  If not, see <http://www.gnu.org/licenses/>.
#

ICONPATH=${ICONPATH:-"./LFSTux.png"}
SOURCEHTML=${SOURCEHTML:-"./mydocset/html"};
DOCSET_NAME=${DOCSET_NAME:-"mydocset"}

DOCSET_NAME="${DOCSET_NAME}.docset"
DOCSET_CONTENTS=${DOCSET_NAME}/Contents
DOCSET_RESOURCES=${DOCSET_CONTENTS}/Resources
DOCSET_DOCUMENTS=${DOCSET_RESOURCES}/Documents
DESTDIR=${DESTDIR:-~/.local/share/Zeal/Zeal/docsets}

mkdir -p ${DESTDIR}/${DOCSET_DOCUMENTS}
cp ${SOURCEHTML}/Tokens.xml ${DESTDIR}/${DOCSET_RESOURCES}
cp ${SOURCEHTML}/Info.plist ${DESTDIR}/${DOCSET_CONTENTS}

if [[ -f "$ICONPATH" ]];then
	convert "$ICONPATH" -resize 16x16 ${DESTDIR}/${DOCSET_NAME}/icon.png
	convert "$ICONPATH" -resize 32x32 ${DESTDIR}/${DOCSET_NAME}/icon@2x.png
fi

pushd ${SOURCEHTML} &>/dev/null
	echo "Copying files ..."
	tar --exclude ${DOCSET_NAME} --exclude Nodes.xml --exclude Tokens.xml --exclude Info.plist --exclude Makefile -c -f - . | (cd ${DESTDIR}/${DOCSET_DOCUMENTS}; tar xf -)
popd &>/dev/null

pushd ${DESTDIR}/${DOCSET_RESOURCES} &>/dev/null
	rm docSet.dsidx||true
	sqlite3 docSet.dsidx <<'END_SQL'
CREATE TABLE searchIndex(id INTEGER PRIMARY KEY, name TEXT, type TEXT, path TEXT);
CREATE UNIQUE INDEX anchor ON searchIndex (name, type, path);
END_SQL

	echo "Building DB ..."
	while read
		do
			unset Name Type Path Anchor
			eval "$REPLY"
			FILEPATH=${Path}
			if [[ ! "X${Anchor}" = "X" ]];then
				FILEPATH="${FILEPATH}#${Anchor}"
			fi
			echo "Adding $Name ..."
			sqlite3 docSet.dsidx  "insert into searchindex (name,type,path) values ('$Name','$Type','$FILEPATH');"
		done< <(kkeditqttagreader Tokens.xml Token Name Type Path Anchor)
	rm Tokens.xml
popd &>/dev/null