#!/bin/bash

FONTNAME=""
SIZE=""

DOCUMENT="$1"
shift

. "$(dirname ${0})/9999-globalFunctions"

if RESULT=$(getFont);then
	FONTNAME=$(echo "$RESULT"|awk -F\| '{print $1}')
	SIZE=$(echo "$RESULT"|awk -F\| '{print $2}')

	echo -n "<span style=\"font-family:${FONTNAME};font-size:${SIZE}px;\">${@}</span>"
fi
