#!/bin/bash

DOCUMENT="$1"
shift

. "$(dirname "${0}")/9999-globalFunctions"

if RESULT=$(getColour);then
	COLOUR=$(echo "$RESULT"|awk -F, '{print $1}')
	echo -n "<span style=\"color:${COLOUR};\">${@}</span>"
fi

