#!/bin/bash

DOCUMENT="$1"
shift

. "$(dirname ${0})/9999-globalFunctions"

TITLE="$(basename "${@}")"
WIDTH=100
HEIGHT=100
RESULT="$TITLE|$WIDTH|$HEIGHT"

if RESULT=$(getImageForm);then
	TITLE=$(echo "$RESULT"|awk -F\| '{print $1}')
	WIDTH=$(echo "$RESULT"|awk -F\| '{print $2}')
	HEIGHT=$(echo "$RESULT"|awk -F\| '{print $3}')

	echo -n "<img src=\"${@}\" alt=\"${@}\" title=\"$TITLE\" height=\"$HEIGHT\" width=\"$WIDTH\">"
fi

