#!/bin/bash

DOCUMENT="$1"
shift

. "$(dirname ${0})/9999-globalFunctions"

TITLE="$(basename "${@}")"
eval $(cat /tmp/htmltagdata)
WIDTH=${WIDTH:-100}
HEIGHT=${HEIGHT:-100}
RESULT="$TITLE|$WIDTH|$HEIGHT"

if RESULT=$(getImageForm);then
	TITLE=$(echo "$RESULT"|awk -F\| '{print $1}')
	WIDTH=$(echo "$RESULT"|awk -F\| '{print $2}')
	HEIGHT=$(echo "$RESULT"|awk -F\| '{print $3}')

	if [[ $WIDTH -gt 0 ]];then
		DOWIDTH=" width=\"$WIDTH\""
	fi
	if [[ $HEIGHT -gt 0 ]];then
		DOHEIGHT=" height=\"$HEIGHT\""
	fi
	echo "WIDTH=$WIDTH" >> /tmp/htmltagdata
	echo "HEIGHT=$HEIGHT" >> /tmp/htmltagdata
	sed -i "s/WIDTH=.*$/WIDTH=${WIDTH}/" /tmp/htmltagdata
	sed -i "s/HEIGHT=.*$/HEIGHT=${HEIGHT}/" /tmp/htmltagdata
	sort -u /tmp/htmltagdata > /tmp/htmltagdata.temp
	mv /tmp/htmltagdata.temp /tmp/htmltagdata
	echo -n "<img src=\"${@}\" alt=\"${@}\" title=\"$TITLE\"${DOHEIGHT}${DOWIDTH}>"
fi
