#!/bin/bash

DOCUMENT="$1"
shift

. "$(dirname ${0})/9999-globalFunctions"

if RESULT=$(getItem "text@button@checkbox@color@date@datetime-local@email@file@hidden@image@month@number@password@radio@range@reset@search@submit@tel@time@url@week");then
	echo "<input type=\"$RESULT\" id=\"$(echo ${@}|sed 's/\s//g')\" value=\"${@}\">"
fi
 

