#!/bin/bash

#©keithhedger Fri 2 Aug 20:08:44 BST 2024 kdhedger68713@gmail.com

echo "Just Open"

DOCSETS=~/.local/share/Zeal/Zeal/docsets
DBNAME=docSet.dsidx
#basic_string
#QFileInfo

DOCSET=$(find ~/.local/share/Zeal/Zeal/docsets -mindepth 4 -maxdepth 4 -iname "*.dsidx"|sort|awk -F/ '{print $(NF  -3) }'|sed -n 's/\(.*\)\.docset/\1/p'|yadqt --type=getitem -t "Search docset" -b "Choose set" --fromstdin --ipseparator=newline)
result=$?

if [[ $result -eq 0 ]];then
	FOLDERNAME=${DOCSETS}/${DOCSET}.docset/Contents/Resources

	HTMLFILE="$2"
	:>"$HTMLFILE"

	echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">">>"$HTMLFILE"
	echo "<html>">>"$HTMLFILE"
	echo "<head>">>"$HTMLFILE"
	echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">">>"$HTMLFILE"
	echo "</head>">>"$HTMLFILE"
	echo "<body>">>"$HTMLFILE"
	echo "<style>">>"$HTMLFILE"
	echo "dl { display: grid; grid-template-columns: max-content auto;}">>"$HTMLFILE"
	echo "dt {grid-column-start: 1;}">>"$HTMLFILE"
	echo "dd {grid-column-start: 2;}">>"$HTMLFILE"
	echo "</style>">>"$HTMLFILE"
	echo "<body>">>"$HTMLFILE"

	DB=${DOCSETS}/${DOCSET}.docset/Contents/Resources/docSet.dsidx
	echo "<span style=\"font-weight: bold;\">Results From ${DOCSET} API's</span></font><dl>" >>"$HTMLFILE"

	foundcnt=0	
	while read ans
		do
			returns="$ans"		
			if [[ ! "X$returns" = "X" ]];then
				((foundcnt++))

				funcname="$(echo "$returns"|awk -F"|" '{print $1}')"
				functype="$(echo "$returns"|awk -F"|" '{print $2}')"
				funcpath="$(echo "$returns"|awk -F"|" '{print $3}')"
				funcpath="${funcpath##?*>}"
				case $functype in
					"func")
						functype="Function";;
					"cl")
						functype="Class";;
					"clm")
						functype="Member";;
					"data")
						functype="Property";;
				esac
#basic_string

				echo "<dt>${functype}</dt><dd><a href=\"file://${FOLDERNAME}/Documents/$funcpath\">${funcname}</a></dd>" >>"$HTMLFILE"
				holdpath="file://${FOLDERNAME}/Documents/$funcpath"
				echo "$funcname"
			fi
		done< <(sqlite3 "$DB" "select name,type,path from searchIndex where name like '%"$1"%' ESCAPE '\' ORDER BY "'type,name'";")

	echo "</body>">>"$HTMLFILE"
	echo "</html>">>"$HTMLFILE"

	if [[ ${foundcnt} -eq 1 ]];then
		echo '<!DOCTYPE html>' >"$HTMLFILE"
		echo '<html>' >>"$HTMLFILE"
		echo '<head>'>>"$HTMLFILE"
		echo '<meta http-equiv="refresh" content="0; url='"$holdpath"'" />' >>"$HTMLFILE"
		echo '</head>' >>"$HTMLFILE"
		echo '</html>' >>"$HTMLFILE"
	fi

fi

exit 100
