#!/bin/bash
#
#©K. D. Hedger. Sat 27 Jul 16:17:02 BST 2024 keithdhedger@gmail.com
#
#This file (searchqt6apis) is part of KKEditQT.
#
#KKEditQT is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#KKEditQT is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with KKEditQT.  If not, see <http://www.gnu.org/licenses/>.
#

DOCSFOLDER="/usr/share/doc/qt6"

echo "Results From QT6 API's"

while read
	do
		FOLD="$(dirname "$(echo "${REPLY}"|awk -F" " '{print $1}')")"
		FILE="$(echo "${REPLY}"|awk -F":" '{print $1}')"
		while read ans
			do
				eval "$ans" 2>/dev/null
				echo "file://${FOLD}/${anchorfile}#${anchor}"
				FROM=$(sed -n 's/.*<title>\(.*\)|.*/\1/p' ${FOLD}/${anchorfile})
				echo "$name from $FROM" 
			done< <(kkeditqttagreader "$REPLY" "member" "name"  "anchorfile"  "anchor"|grep -i "${1}")
	done< <(find "$DOCSFOLDER" -iname "*.tags")
exit 0

