#!/bin/bash

#©keithhedger Sat 6 Jul 13:32:17 BST 2024 kdhedger68713@gmail.com

echo "Results From QT6 API's"

while read
	do
		echo "$REPLY"
		basename "$REPLY" .html
	done < <(/usr/sbin/find /usr/share/doc/qt6 -iname "$1*.html"|/usr/sbin/sort)

