#!/bin/bash

#©keithhedger Sat 6 Jul 13:32:17 BST 2024 kdhedger68713@gmail.com

DOCSFOLDER="/usr/share/doc/qt6"

echo "Results From QT6 Classes"

while read
	do
		echo "$REPLY"
		basename "$REPLY" .html
	done < <(/usr/sbin/find "$DOCSFOLDER" -iname "$1.html"|/usr/sbin/sort)

